const { isProduction } = require("../src/_data/meta");
const htmlmin = require("html-minifier-terser");

module.exports = function(config) {
  config.addTransform("htmlmin", function(content) {
    if(this.page.outputPath && this.page.outputPath.endsWith(".html") && isProduction) {
      return htmlmin.minify(content, {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        includeAutoGeneratedTags: false,
        removeComments: true,
        minifyCSS: true,
        minifyJS: true
      });
    }

    return content;
  });
};